commands:
  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: my-magento-ce-1.9.1.1
        version: 1.9.1.1
        dist:
          url: http://www.magentocommerce.com/downloads/assets/1.9.1.1/magento-1.9.1.1.tar.gz
          type: tar
        extra:
          sample-data: my-sample-data-1.9.1.0

      - name: example-tar-magento
        version: 0.0.0.0
        dist:
          url: http://www.example.com/downloads/magento-0.0.0.0.tar.gz
          type: tar
        extra:
          sample-data: my-sample-data-1.9.1.0

      - name: example-git-magento
        version: 0.0.0.0
        source:
          url: git://github.com/tunght13488/magento.git
          type: git
          reference: magento-ce-0.0
        extra:
          sample-data: my-sample-data-1.9.1.0

    demo-data-packages:
      - name: my-sample-data-1.9.1.0
        version: 1.9.1.0
        dist:
          url: https://raw.githubusercontent.com/Vinai/compressed-magento-sample-data/1.9.1.0/compressed-magento-sample-data-1.9.1.0.tgz
          type: tar

    installation:
      defaults:
        currency: USD
        locale: en_US
        timezone: Asia/Ho_Chi_Minh
        session_save: files
        admin_username: admin
        admin_firstname: John
        admin_lastname: Doe
        admin_password: admin123
        admin_frontname: admin
        admin_email: john.doe@example.com
        encryption_key:
